name: "Clementine.js"
description: "The elegant and lightweight boilerplate for full stack JavaScript."
url: http://www.clementinejs.com
baseurl: /
highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
